# Q3 — For every person (Employees and Customers) list their full name,
# a bool which is true if the person has at least one phone number,
# and a quantity of the phone numbers the person has.

PREFIX ex: <https://exmaple.org/vocabulary/>
PREFIX schema: <https://schema.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#>

SELECT ?fullName ?hasTelephone (COUNT(DISTINCT ?telephone) AS ?telephoneCount)
WHERE
{
  ?person a ?class;
          ex:fullName ?fullName .

  ?class rdfs:subClassOf foaf:Person .

  OPTIONAL
  {
    ?person foaf:phone ?telephone .
  }

  # true if has at least one telephone number
  BIND(BOUND(?telephone) AS ?hasTelephone)
}
GROUP BY ?fullName ?hasTelephone
ORDER BY ASC(?fullName) ASC(?telephoneCount)
