
# Q2 — Construct RDF triples that represent each shop
# together with the number of customers it serves,
# but only include shops that serve more than 1 customer.
PREFIX ex:     <https://exmaple.org/vocabulary/>
PREFIX schema: <https://schema.org/>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
  # For each selected shop, create triples of the form:  
CONSTRUCT {                                  
?shop a schema:LocalBusiness ;
        rdf:value ?customerCount .
}
WHERE {
     ?shop a schema:LocalBusiness .

{
 #Subquery to count how many customers each shop serve
      SELECT ?shop (COUNT(DISTINCT ?customer) AS ?customerCount)    
          WHERE {
               ?shop ex:serves ?customer .
          }
    GROUP BY ?shop
  }

  FILTER(?customerCount > 1) # keeps only the shops where the number of customers > 1
}

